### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-app-text-analysis#13]
add contributors to readme

**Comment by juancarlosfarah** [comment]
@allcontributors please add @fannylsn and @spaenleh for code, ideas, design.

**Comment by juancarlosfarah** [comment]
@allcontributors,
1. please add @spaenleh for code, ideas, design.
2. please add @juancarlosfarah for code, ideas, design.

**Comment by spaenleh** [comment]
@allcontributors add @spaenleh for code, ideas and design

**Comment by spaenleh** [comment]
@allcontributors add @juancarlosfarah for code, idea and design
